### ISSUE TITLE
img tag

### ISSUE THREAD

**Issue by justinrummel** [octopress/octopress#70]
While testing a migration from my Octopress 2 site, I noticed an error for the "img" tag that was a default option in Octopress 2 ( http://octopress.org/docs/plugins/image-tag/ ) was missing.  Should this be substituted with a jekyll plugin in my Gemfile or should we pull from  https://github.com/imathis/octopress/blob/master/plugins/image_tag.rb 

With some plugins missing, it also seems odd that the _plugins folder is not created by default when doing a "octopress new".

**Comment by imathis** [comment]
I'm working on adding stand-alone plugin to replace what's in Octopress 2.0 (with tests!) but I haven't done them all yet. The reason there isn't a _plugins directory is that `jekyll new` doesn't add it and Octopress uses Jekyll's scaffolding but adds its own.

**Comment by imathis** [comment]
I've just released 1.0.0 of octopress-image-tag. Which you can find here: https://github.com/octopress/image-tag. It should be a drop in replacement for the plugin you're currently using.

**Comment by e9t** [comment]
I've added `gem 'octopress-image-tag'` to my `Gemfile`

<pre>
source 'https://rubygems.org'
 
gem 'jekyll'
 
group :jekyll_plugins do
    gem 'octopress', '~> 3.0.0.rc'
    gem 'octopress-image-tag'
end
</pre>

and `bundle update`d, 
but I'm still getting an error.

<pre>
Configuration file: /Users/e9t/dev/sites/lucypark.kr/source/_config.yml
            Source: /Users/e9t/dev/sites/lucypark.kr/source
       Destination: /Users/e9t/dev/sites/lucypark.kr/source/_site
      Generating... 
  Liquid Exception: Unknown tag 'img' in _posts/2010-01-27-data-reduction-and-data-production.markdown
jekyll 2.5.3 | Error:  Unknown tag 'img'
</pre>

Am I missing a step or doing something wrong?

**Comment by busches** [comment]
You need to add it to the `_config.yml` file as well.

**Comment by e9t** [comment]
Ah, that fixes it. Thanks @busches!

**Comment by imathis** [comment]
Thanks for the assist @busches!
